### ISSUE TITLE
Quick undo/redo calls break the usage

### ISSUE THREAD

**Issue by brunocalou** [homerchen19/use-undo#28]
Hello,

I have found a bug. When I call redo quickly, the state breaks the application. The present state becomes undefined.

## Steps to reproduce
1. Go to [this sandbox](https://codesandbox.io/s/use-undo-demo-forked-uo978?file=/src/App.tsx)
2. Click on `+` twice
3. Click on `undo`
4. Click on `double redo`

The `present` becomes undefined and shows `Oh snap!` text

I believe it happens because `canUndo/canRedo` on the lib are updated just after the state changes. A quick `undo/redo` dispatch the `Undo/Redo` actions twice, because the `canUndo/canRedo` was not updated yet.

I'm working on a solution 👍

**Comment by homerchen19** [comment]
Thank you!
